### PR TITLE
Bug/fix-connector-x-initial

### PR DESCRIPTION
**Pull request by having11**
# Description of pull request

This PR fixes a few issues with the Connector-X module not responding to pattern commands correctly and removes the second core's functionality for simplicity

## List of changes

- Fix pattern/LED issues
- Use a single core
- Verify GPIO works as expected

## Before you merge

- [X] Compiles
- [x] Unit tests pass
- [X] Tested on the robot
- [ ] Reviewed by another member

### CODE REVIEW

**Review by nobody5050 — COMMENTED** [review]
Is there any reason why some changed code is commented out and some is removed?

**Comment by having11** [comment]
> Is there any reason why some changed code is commented out and some is removed?

I haven't gotten the EEPROM chip working yet, so for now we're using the emulated flash-based EEPROM in the RP2040. Commented-out code will be re-added shortly whereas removed code is gone.

**Review by nobody5050 — APPROVED** [review]
LGTM! 🚀 🌕 ⭐ 📈

**Review by 5690Programmers — APPROVED** [review]
LGTM

**Pull request merged**
